### ISSUE TITLE
Error info

### ISSUE THREAD

**Issue by chaoshengt** [CNFeffery/FefferyViz#1]
There is an error info when I run the code of "(在模仿中精进数据可视化01) 国内38城居住自由指数可视化:
```python
ValueError                                Traceback (most recent call last)
Cell In[18], line 33
     30 text_data.loc[20:, '锚点纬度'] = text_data.loc[20:, '购房自由指数_映射值':'租房自由指数_映射值'].max(axis=1) + 1.5
     31 text_data['geometry'] = [Point(lng, lat) for lng, lat in zip(np.arange(10, 220, 210 / data.shape[0]),
     32                                                              text_data['锚点纬度'])]
---> 33 text_data = gpd.GeoDataFrame(text_data, crs='EPSG:4326').to_crs()
     34 # text_data = gpd.GeoDataFrame(text_data).set_crs(crs,allow_override=False)
     36 for row in text_data.loc[:19].itertuples():

File D:\anaconda3\lib\site-packages\geopandas\geodataframe.py:148, in GeoDataFrame.__init__(self, data, geometry, crs, *args, **kwargs)
    146     self._geometry_column_name = data._geometry_column_name
    147     if crs is not None and data.crs != crs:
--> 148         raise ValueError(crs_mismatch_error)
    150 if (
    151     geometry is None
    152     and self.columns.nlevels == 1
   (...)
    156     # self["geometry"] is a gdf and constructor gets recursively recalled
    157     # by pandas internals trying to access this
    158     if (self.columns == "geometry").sum() > 1:

ValueError: CRS mismatch between CRS of the passed geometries and 'crs'. Use 'GeoDataFrame.set_crs(crs, allow_override=True)' to overwrite CRS or 'GeoDataFrame.to_crs(crs)' to reproject geometries. 
```
How to solve it? thank you. :)

**Comment by chaoshengt** [comment]
> There is an error info when I run the code of "(在模仿中精进数据可视化01) 国内38城居住自由指数可视化:
> 
> ```python
> ValueError                                Traceback (most recent call last)
> Cell In[18], line 33
>      30 text_data.loc[20:, '锚点纬度'] = text_data.loc[20:, '购房自由指数_映射值':'租房自由指数_映射值'].max(axis=1) + 1.5
>      31 text_data['geometry'] = [Point(lng, lat) for lng, lat in zip(np.arange(10, 220, 210 / data.shape[0]),
>      32                                                              text_data['锚点纬度'])]
> ---> 33 text_data = gpd.GeoDataFrame(text_data, crs='EPSG:4326').to_crs()
>      34 # text_data = gpd.GeoDataFrame(text_data).set_crs(crs,allow_override=False)
>      36 for row in text_data.loc[:19].itertuples():
> 
> File D:\anaconda3\lib\site-packages\geopandas\geodataframe.py:148, in GeoDataFrame.__init__(self, data, geometry, crs, *args, **kwargs)
>     146     self._geometry_column_name = data._geometry_column_name
>     147     if crs is not None and data.crs != crs:
> --> 148         raise ValueError(crs_mismatch_error)
>     150 if (
>     151     geometry is None
>     152     and self.columns.nlevels == 1
>    (...)
>     156     # self["geometry"] is a gdf and constructor gets recursively recalled
>     157     # by pandas internals trying to access this
>     158     if (self.columns == "geometry").sum() > 1:
> 
> ValueError: CRS mismatch between CRS of the passed geometries and 'crs'. Use 'GeoDataFrame.set_crs(crs, allow_override=True)' to overwrite CRS or 'GeoDataFrame.to_crs(crs)' to reproject geometries. 
> ```
> 
> How to solve it? thank you. :)

I have fixed it. change this line
```python
text_data = gpd.GeoDataFrame(text_data, crs='EPSG:4326').to_crs(crs)
```
to
```python
text_data=text_data.set_crs(crs='EPSG:4326', allow_override=True).to_crs(crs)
```

Thank you for sharing.

**Comment by CNFeffery** [comment]
This is due to geopandas's upgrade.
